# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'cruisin66v1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 use_frameworks!

  # Pods for cruisin66v1
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
# pod 'GoogleMaps'
# pod 'Google-Maps-iOS-Utils'
  # target 'cruisin66v1-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end


  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'




  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # target 'cruisin66v1Tests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'cruisin66v1-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for cruisin66v1-tvOS

#   # target 'cruisin66v1-tvOSTests' do
#   #   inherit! :search_paths
#   #   # Pods for testing
#   # end

# end
